
insert into Growing (CropID, FieldID) values (1, 1);
insert into Growing (CropID, FieldID) values (1, 2);
insert into Growing (CropID, FieldID) values (1, 3);
insert into Growing (CropID, FieldID) values (1, 4);
insert into Growing (CropID, FieldID) values (1, 5);
insert into Growing (CropID, FieldID) values (1, 6);
insert into Growing (CropID, FieldID) values (1, 7);
insert into Growing (CropID, FieldID) values (2, 8);
insert into Growing (CropID, FieldID) values (2, 9);
insert into Growing (CropID, FieldID) values (2, 3);
insert into Growing (CropID, FieldID) values (2, 4);
insert into Growing (CropID, FieldID) values (3, 5);
insert into Growing (CropID, FieldID) values (3, 6);
insert into Growing (CropID, FieldID) values (3, 8);
insert into Growing (CropID, FieldID) values (3, 9);
insert into Growing (CropID, FieldID) values (3, 10);
insert into Growing (CropID, FieldID) values (3, 11);
insert into Growing (CropID, FieldID) values (4, 16);
insert into Growing (CropID, FieldID) values (5, 13);
insert into Growing (CropID, FieldID) values (5, 14);
insert into Growing (CropID, FieldID) values (5, 15);
insert into Growing (CropID, FieldID) values (6, 14);
insert into Growing (CropID, FieldID) values (6, 18);
insert into Growing (CropID, FieldID) values (7, 19);
insert into Growing (CropID, FieldID) values (7, 1);
insert into Growing (CropID, FieldID) values (8, 1);
insert into Growing (CropID, FieldID) values (6, 3);
insert into Growing (CropID, FieldID) values (9, 12);
insert into Growing (CropID, FieldID) values (10, 11);
insert into Growing (CropID, FieldID) values (11,12);
insert into Growing (CropID, FieldID) values (11,13);
insert into Growing (CropID, FieldID) values (11, 14);
insert into Growing (CropID, FieldID) values (11, 15);
